image: node:latest

stages:
  - deploy

before_script:
  - npm install

deploy:
  stage: deploy
  script:
    - echo //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN} >> .npmrc
    - echo //gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} >> .npmrc
    - npm run build-ts
    - npm publish
